import argparse
import json
import os
import tempfile
import time
from pathlib import Path
from urllib.parse import urlparse

import requests

from stage1_common import load_env_file


def infer_filename(url: str, fallback_name: str) -> str:
    path_name = Path(urlparse(url).path).name
    return path_name or fallback_name


def prepare_netrc(username: str, password: str) -> Path:
    content = (
        f"machine urs.earthdata.nasa.gov login {username} password {password}\n"
        f"machine data.lpdaac.earthdatacloud.nasa.gov login {username} password {password}\n"
    )
    fd, tmp_name = tempfile.mkstemp(prefix="earthdata_", suffix=".netrc")
    with os.fdopen(fd, "w", encoding="utf-8") as f:
        f.write(content)
    os.environ["NETRC"] = tmp_name
    return Path(tmp_name)


def build_session() -> requests.Session:
    username = os.environ.get("EARTHDATA_USERNAME", "")
    password = os.environ.get("EARTHDATA_PASSWORD", "")
    if not username or not password:
        raise RuntimeError("EARTHDATA_USERNAME or EARTHDATA_PASSWORD is missing.")
    prepare_netrc(username, password)
    session = requests.Session()
    session.headers.update({"User-Agent": "sr-weather-stage1-downloader/0.1"})
    return session


def download_with_retry(
    session: requests.Session,
    url: str,
    output_path: Path,
    retries: int,
    retry_sleep_seconds: float,
) -> bool:
    tmp_path = output_path.with_name(output_path.name + ".part")
    last_error = None
    for attempt in range(1, retries + 1):
        try:
            with session.get(url, stream=True, timeout=300, allow_redirects=True) as response:
                response.raise_for_status()
                with tmp_path.open("wb") as f:
                    for chunk in response.iter_content(chunk_size=1024 * 1024):
                        if chunk:
                            f.write(chunk)
            os.replace(tmp_path, output_path)
            return True
        except requests.RequestException as exc:
            last_error = exc
            if tmp_path.exists():
                tmp_path.unlink()
            print(f"WARN attempt={attempt}/{retries} failed for {output_path.name}: {exc}")
            if attempt < retries:
                time.sleep(retry_sleep_seconds * attempt)
    print(f"FAIL {output_path.name}: {last_error}")
    return False


def main() -> None:
    parser = argparse.ArgumentParser(description="Download Earthdata files from a JSON manifest.")
    parser.add_argument("--manifest", required=True, help="Path to manifest JSON generated by list_nasa_cmr_granules.py")
    parser.add_argument("--output-dir", required=True, help="Directory to store downloaded files")
    parser.add_argument(
        "--env-file",
        default="25to1/configs/stage1_credentials.example.env",
        help="Optional env file to load before reading credentials",
    )
    parser.add_argument("--limit", type=int, default=0, help="Optional max number of files to download")
    parser.add_argument("--retries", type=int, default=5, help="Retry count per file for transient network failures.")
    parser.add_argument("--retry-sleep-seconds", type=float, default=2.0, help="Base backoff sleep in seconds.")
    args = parser.parse_args()

    load_env_file(Path(args.env_file).resolve())
    manifest_path = Path(args.manifest).resolve()
    output_dir = Path(args.output_dir).resolve()
    output_dir.mkdir(parents=True, exist_ok=True)

    records = json.loads(manifest_path.read_text(encoding="utf-8"))
    session = build_session()

    downloaded = 0
    skipped = 0
    failed = 0
    for idx, record in enumerate(records, start=1):
        url = record.get("download_url")
        granule_id = record.get("granule_id", f"record_{idx:04d}")
        if not url:
            skipped += 1
            print(f"SKIP {granule_id}: no download_url")
            continue

        filename = infer_filename(url, f"{granule_id}.bin")
        output_path = output_dir / filename
        if output_path.exists():
            skipped += 1
            print(f"SKIP {granule_id}: exists -> {output_path.name}")
            continue

        print(f"GET  {granule_id} -> {output_path.name}")
        ok = download_with_retry(
            session=session,
            url=url,
            output_path=output_path,
            retries=args.retries,
            retry_sleep_seconds=args.retry_sleep_seconds,
        )
        if ok:
            downloaded += 1
        else:
            failed += 1
        if args.limit and downloaded >= args.limit:
            break

    print(f"Done. downloaded={downloaded} skipped={skipped} failed={failed} output_dir={output_dir}")


if __name__ == "__main__":
    main()
